import type { Skill } from "./models";

export enum DeathBladeSkills {
    DeathTrance = 25030,
    DeathlySlash = 25440,
    BreakingMoon = 25430,
    SoulAbsorber = 25110,
    DeathSentence = 25080,
    VoidStrike = 25180,
    TwinShadows = 25090,
    TurningSlash = 25130,
    EarthCleaver = 25070,
    BladeAssault = 25350,
    Maelstrom = 25160,
    Spincutter = 25120,
    EternalFlash = 25410,
    ChaoticDeathblade = 25420
}

export type SkillTemplate = Pick<Skill, "id" | "ratio" | "castTime" | "name" | "iconSrc" | "cooldown" | "isHyperAwakening" | "identityGain" | "isHyperAwakeningTechnique">;

export const templateSkills: SkillTemplate[] = [
    {
        id: 25030,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 250,
        identityGain: 0,
        castTime: 0.25,
        name: "Death Trance",
        iconSrc: "./images/skills/BL_Skill_01_20.webp",
        cooldown: 30
    },
    {
        id: 25430,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: true,
        ratio: 150,
        identityGain: 1,
        castTime: 1,
        name: "Breaking Moon",
        iconSrc: "./images/skills/BL_Skill_01_26.webp",
        cooldown: 180,
    },
    {
        id: 25440,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: true,
        ratio: 100,
        identityGain: 1.5,
        castTime: 0.25,
        name: "Deathly Slash",
        iconSrc: "./images/skills/BL_Skill_01_27.webp",
        cooldown: 60,
    },
    {
        id: 25110,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 100,
        identityGain: 1,
        castTime: 0.25,
        name: "Soul Absorber",
        iconSrc: "./images/skills/BL_Skill_01_7.webp",
        cooldown: 24,
    },
    {
        id: 25080,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 100,
        identityGain: 1,
        castTime: 0.25,
        name: "Death Sentence",
        iconSrc: "./images/skills/BL_Skill_01_4.webp",
        cooldown: 18,
    },
    {
        id: 25180,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 100,
        identityGain: 1.5,
        castTime: 0.25,
        name: "Void Strike",
        iconSrc: "./images/skills/BL_Skill_01_14.webp",
        cooldown: 27,
    },
    {
        id: 25090,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 100,
        identityGain: 0.5,
        castTime: 0.25,
        name: "Twin Shadows",
        iconSrc: "./images/skills/BL_Skill_01_5.webp",
        cooldown: 15,
    },
    {
        id: 25130,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 100,
        identityGain: 0.5,
        castTime: 0.25,
        name: "Turning Slash",
        iconSrc: "./images/skills/BL_Skill_01_9.webp",
        cooldown: 15,
    },
    {
        id: 25070,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 100,
        identityGain: 0.25,
        castTime: 0.25,
        name: "Earth Cleaver",
        iconSrc: "./images/skills/BL_Skill_01_3.webp",
        cooldown: 16,
    },
    {
        id: 25350,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 100,
        identityGain: 3,
        castTime: 0.25,
        name: "Blade Assault",
        iconSrc: "./images/skills/BL_Skill_01_19.webp",
        cooldown: 300,
    },
    {
        id: 25160,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 1,
        identityGain: 0.1,
        castTime: 0.25,
        name: "Maelstrom",
        iconSrc: "./images/skills/BL_Skill_01_12.webp",
        cooldown: 30,
    },
    {
        id: 25120,
        isHyperAwakening: false,
        isHyperAwakeningTechnique: false,
        ratio: 1,
        identityGain: 0.25,
        castTime: 0.25,
        name: "Spincutter",
        iconSrc: "./images/skills/BL_Skill_01_8.webp",
        cooldown: 12,
    },
    {
        id: 25410,
        isHyperAwakening: true,
        isHyperAwakeningTechnique: false,
        ratio: 100,
        identityGain: 3,
        castTime: 3,
        name: "Eternal Flash",
        iconSrc: "./images/skills/BL_Skill_01_24.webp",
        cooldown: 300,
    },
    {
        id: 25420,
        isHyperAwakening: true,
        isHyperAwakeningTechnique: false,
        ratio: 100,
        identityGain: 3,
        castTime: 3,
        name: "Chaotic Deathblade",
        iconSrc: "./images/skills/BL_Skill_01_25.webp",
        cooldown: 300,
    },
];